version: "3.9"

services:
  mysql_db:
    container_name: musicology_db
    image: mysql:8
    env_file: .env.db
    restart: unless-stopped
    # command: 
    #   - --default-authentication-plugin=mysql_native_password
    #   - --sql_mode=
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - musicology
  
  backend:
    container_name: musicology_api
    image: ${ECR_REGISTRY}/${ECR_BREPO_NAME}:${IMAGE_TAG}
    env_file: .env.backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    networks:
      - musicology
  
  frontend:
    container_name: musicology_pro
    image: ${ECR_REGISTRY}/${ECR_FREPO_NAME}:${IMAGE_TAG}
    env_file: .env.frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - musicology

networks:
  musicology:
    name: musicology
  